// The Worker's entry point (wrangler.jsonc "main"). It wraps the Next.js app built by OpenNext
// and adds what a Next.js app can't do on its own:
//   - /realtime: WebSockets for live updates, held by a RealtimeHub Durable Object per user
//   - /board-live: live whiteboards, one BoardRoom Durable Object per board
//   - a light path for the busiest small API calls (./fast-api.ts)
//   - scheduled(): the daily cron job (quiz reminders), see src/app/api/cron/daily/route.ts, and
//     the spending guard every 15 minutes (./usage-guard.ts)
import { DurableObject } from 'cloudflare:workers';
import * as Y from 'yjs';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- the file only exists after a build
// @ts-ignore: generated by `opennextjs-cloudflare build`
import nextApp from '../.open-next/worker.js';
import { fastApi } from './fast-api';
import { dbDate } from './fast-db';
import { checkUsage, pageNotice, serverGate, withNotice } from './usage-guard';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- the file only exists after a build
// @ts-ignore: generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from '../.open-next/worker.js';

interface Env {
  ASSETS?: Fetcher;
  DB?: D1Database;
  REALTIME: DurableObjectNamespace<RealtimeHub>;
  BOARDS?: DurableObjectNamespace<BoardRoom>;
  CODE?: DurableObjectNamespace<CodeRoom>;
  CALLS?: DurableObjectNamespace<CallRoom>;
  API_RATE_LIMITER?: RateLimit; // per signed-in user (or per IP when signed out)
  IP_RATE_LIMITER?: RateLimit; // per IP, generous: stops floods from one address
  COSTLY_RATE_LIMITER?: RateLimit; // per user, for AI, email and uploads
  [key: string]: unknown;
}

// Endpoints that cost money or send email per call.
const COSTLY = /^\/api\/(ai|summarize|premium\/ai-report|support|upload|core\/files\/upload|core\/safety\/report|student\/guardians|chat\/translate-draft|chat\/conversations\/[^/]+\/translate|tutor\/(?!cards)[^/]+\/(ask|practice|flashcards|sources)|assignments\/submissions\/[^/]+\/draft)(\/|$)/;

const tooMany = () =>
  Response.json({ error: 'Too many requests. Please wait a minute and try again.' }, { status: 429, headers: { 'Retry-After': '60' } });

/**
 * Rate limits for the API and live updates. Keyed by the signed-in user (the end of their token)
 * so a whole campus behind one Wi-Fi address isn't treated as one person, plus a generous
 * per-address cap against floods. Limiter checks are free and don't count as requests.
 */
async function rateLimited(request: Request, url: URL, env: Env): Promise<boolean> {
  const ip = request.headers.get('cf-connecting-ip') ?? 'unknown';
  const token = request.headers.get('authorization')?.slice(-40);
  // Live connections can't send headers: they carry the user (and a one-time ticket) in the
  // address, so count them per user too, not per shared campus address.
  const live = url.pathname === '/realtime' ? url.searchParams.get('user') : url.pathname === '/board-live' || url.pathname === '/code-live' || url.pathname === '/call-live' ? url.searchParams.get('ticket') : null;
  const who = token ? `u:${token}` : live ? `live:${live.slice(0, 80)}` : `ip:${ip}`;
  const checks: Promise<{ success: boolean }>[] = [];
  if (env.IP_RATE_LIMITER) checks.push(env.IP_RATE_LIMITER.limit({ key: ip }));
  if (env.API_RATE_LIMITER) checks.push(env.API_RATE_LIMITER.limit({ key: who }));
  if (env.COSTLY_RATE_LIMITER && request.method !== 'GET' && COSTLY.test(url.pathname)) checks.push(env.COSTLY_RATE_LIMITER.limit({ key: who }));
  return (await Promise.all(checks)).some((r) => !r.success);
}

/**
 * Pages (HTML and in-app navigation data) come with Next's `s-maxage=…, stale-while-revalidate=…`,
 * meant for a shared cache. Browsers that honour stale-while-revalidate (Safari) could then show a
 * copy from before the last update, even after a refresh, and that copy points at files the update
 * removed. `no-cache` makes the browser check each time (a cheap 304 when nothing changed).
 */
function revalidatePages(request: Request, res: Response): Response {
  const type = res.headers.get('content-type') ?? '';
  if (!/^text\/(html|x-component)/.test(type) || !/s-maxage|stale-while-revalidate/.test(res.headers.get('cache-control') ?? '')) return res;
  // Unchanged since the browser's copy: just say so.
  const etag = res.headers.get('etag');
  if (etag && request.headers.get('if-none-match') === etag) return new Response(null, { status: 304, headers: { ETag: etag, 'Cache-Control': 'no-cache' } });
  const out = new Response(res.body, res);
  out.headers.set('Cache-Control', 'no-cache');
  return out;
}

// The build these pages belong to (public/BUILD_ID), read once per instance: cached pages are kept
// per build, so a deploy never serves pages that point at the previous build's files.
let buildId: Promise<string | null> | null = null;
function currentBuild(origin: string, env: Env) {
  buildId ??= (env.ASSETS ? env.ASSETS.fetch(`${origin}/BUILD_ID`).then((r) => (r.ok ? r.text() : null)).then((t) => t?.trim() || null) : Promise.resolve(null)).catch(() => {
    buildId = null;
    return null;
  });
  return buildId;
}

/**
 * Pages that are the same for everyone (Next.js built them ahead of time: the home page, sign-in,
 * the dashboards' shells, legal pages) are kept in Cloudflare's cache near the visitor. A repeat
 * visit is then answered without starting the Next.js app at all: a faster first screen, and no
 * CPU time for the free plan's limit. In-app navigation data (RSC requests) still goes to Next.js.
 */
async function edgeCachedPage(request: Request, url: URL, env: Env, ctx: ExecutionContext, render: () => Promise<Response>): Promise<Response> {
  // An address with ?… (the page recovery's one-off retry, links with tracking tags) always gets a
  // fresh copy from Next.js.
  const plain = request.method === 'GET' && !url.search && !request.headers.has('rsc') && !request.headers.has('next-router-prefetch') && !request.headers.has('authorization') && !request.headers.has('range');
  const build = plain ? await currentBuild(url.origin, env) : null;
  if (!build) return revalidatePages(request, await render());
  const cache = (caches as unknown as { default: Cache }).default;
  const key = new Request(`${url.origin}${url.pathname}?__build=${encodeURIComponent(build)}`);
  const hit = await cache.match(key).catch(() => undefined);
  if (hit) {
    const etag = hit.headers.get('etag');
    if (etag && request.headers.get('if-none-match') === etag) return new Response(null, { status: 304, headers: { ETag: etag, 'Cache-Control': 'no-cache' } });
    const out = new Response(hit.body, hit);
    out.headers.set('Cache-Control', 'no-cache');
    return out;
  }
  const res = await render();
  const sameForEveryone = res.status === 200 && res.headers.get('x-nextjs-prerender') === '1' && /^text\/html/.test(res.headers.get('content-type') ?? '') && /s-maxage/.test(res.headers.get('cache-control') ?? '') && !res.headers.has('set-cookie');
  if (sameForEveryone) {
    const copy = new Response(res.clone().body, res);
    copy.headers.set('Cache-Control', 'public, max-age=86400');
    ctx.waitUntil(cache.put(key, copy).catch(() => {}));
  }
  return revalidatePages(request, res);
}

const DAILY_CRON = '0 8 * * *'; // wrangler.jsonc "triggers"; the */15 one is the spending guard
const DIGEST_CRON = '30 7 * * *'; // the owner's morning summary email (src/server/owner-digest.ts)

const TICKET_TTL_MS = 60_000;
const MAX_SOCKETS = 20; // per user: app + a few browser tabs

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    // Paused (spending guard or maintenance) or read-only: answered here, without running the app.
    const gate = serverGate(request, url, env, ctx);
    if (gate) return gate;
    // Stripe's webhook is signed and comes from Stripe's servers, so it's never rate limited.
    if ((url.pathname.startsWith('/api/') && !url.pathname.startsWith('/api/webhooks/')) || url.pathname === '/realtime' || url.pathname === '/board-live' || url.pathname === '/code-live' || url.pathname === '/call-live') {
      if (await rateLimited(request, url, env)) return tooMany();
    }
    if (url.pathname === '/realtime') {
      if (request.headers.get('Upgrade')?.toLowerCase() !== 'websocket') return new Response('Expected a WebSocket', { status: 426 });
      const user = url.searchParams.get('user');
      if (!user || !url.searchParams.get('ticket') || !env.REALTIME) return new Response('Forbidden', { status: 403 });
      return env.REALTIME.get(env.REALTIME.idFromName(user)).fetch(request);
    }
    if (url.pathname === '/board-live') {
      if (request.headers.get('Upgrade')?.toLowerCase() !== 'websocket') return new Response('Expected a WebSocket', { status: 426 });
      const board = url.searchParams.get('board');
      if (!board || !url.searchParams.get('ticket') || !env.BOARDS) return new Response('Forbidden', { status: 403 });
      return env.BOARDS.get(env.BOARDS.idFromName(board)).fetch(request);
    }
    if (url.pathname === '/code-live') {
      if (request.headers.get('Upgrade')?.toLowerCase() !== 'websocket') return new Response('Expected a WebSocket', { status: 426 });
      const room = url.searchParams.get('room');
      if (!room || !url.searchParams.get('ticket') || !env.CODE) return new Response('Forbidden', { status: 403 });
      return env.CODE.get(env.CODE.idFromName(room)).fetch(request);
    }
    if (url.pathname === '/call-live') {
      if (request.headers.get('Upgrade')?.toLowerCase() !== 'websocket') return new Response('Expected a WebSocket', { status: 426 });
      const callId = url.searchParams.get('call');
      if (!callId || !url.searchParams.get('ticket') || !env.CALLS) return new Response('Forbidden', { status: 403 });
      return env.CALLS.get(env.CALLS.idFromName(callId)).fetch(request);
    }
    const fast = url.pathname.startsWith('/api/') ? await fastApi(request, url, env, ctx, (r) => nextApp.fetch(r, env, ctx)) : null;
    if (fast) return fast;
    // No www → main address redirect: phones that installed the app from www.universeimpact.com
    // were sent outside their app (and its saved files) on every launch.
    if (url.pathname.startsWith('/api/') || url.pathname.startsWith('/_next/')) return revalidatePages(request, await nextApp.fetch(request, env, ctx));
    return withNotice(await edgeCachedPage(request, url, env, ctx, () => nextApp.fetch(request, env, ctx)), pageNotice());
  },

  async scheduled(controller: ScheduledController, env: Env, ctx: ExecutionContext) {
    let job = controller.cron === DIGEST_CRON ? 'digest' : 'daily';
    if (controller.cron !== DAILY_CRON && controller.cron !== DIGEST_CRON) {
      console.log(`spending guard: ${await checkUsage(env)}`);
      // Scheduled-call reminders: one cheap query; the app only starts when a call is due.
      if (!(await callsDue(env))) return;
      job = 'reminders';
    }
    // Run the job inside the Next.js app (where the database code lives). The random token only
    // exists in this isolate, so the route can't be triggered from outside.
    const token = crypto.randomUUID();
    (globalThis as { __universeCronToken?: string }).__universeCronToken = token;
    const res: Response = await nextApp.fetch(
      new Request(`https://universeimpact.com/api/cron/${job}`, { method: 'POST', headers: { 'x-cron-token': token } }),
      env,
      ctx,
    );
    console.log(`cron ${controller.cron}: ${res.status} ${await res.text()}`);
    if (!res.ok) throw new Error(`Cron job ${job} failed with ${res.status}`);
  },
};

/** Is a scheduled call starting within about 15 minutes, a chat reminder due, a study plan's
 *  7-day follow-up due, or a chat message scheduled for now, not yet sent? */
async function callsDue(env: Env): Promise<boolean> {
  if (!env.DB) return false;
  const now = Date.now();
  try {
    // A scheduled call starting soon, or a "/remind" reminder that's due.
    const row = await env.DB.prepare(
      `SELECT 1 FROM scheduled_calls WHERE "remindedAt" IS NULL AND "startAt" > ?1 AND "startAt" <= ?2
       UNION ALL SELECT 1 FROM chat_reminders WHERE "sentAt" IS NULL AND "dueAt" <= ?3
       UNION ALL SELECT 1 FROM support_plans WHERE "status" = 'ACTIVE' AND "followUpNotifiedAt" IS NULL AND "followUpAt" <= ?3
       UNION ALL SELECT 1 FROM scheduled_messages WHERE "sendAt" <= ?4 LIMIT 1`,
    )
      .bind(dbDate(now - 5 * 60_000), dbDate(now + 16 * 60_000), dbDate(now + 5 * 60_000), dbDate(now + 2 * 60_000))
      .first();
    return !!row;
  } catch (e) {
    console.error('scheduled-call check failed:', e);
    return false;
  }
}

/**
 * One per user: holds that user's open WebSockets (hibernating while idle, so an open tab costs
 * nothing between events) and forwards "something changed" events to them.
 */
export class RealtimeHub extends DurableObject<Env> {
  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    // Keep-alive pings are answered without waking the object.
    this.ctx.setWebSocketAutoResponse(new WebSocketRequestResponsePair('ping', 'pong'));
  }

  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === '/ticket' && request.method === 'POST') {
      const now = Date.now();
      const stale = [...(await this.ctx.storage.list<number>({ prefix: 'ticket:' }))].filter(([, exp]) => exp < now).map(([k]) => k);
      if (stale.length) await this.ctx.storage.delete(stale.slice(0, 128));
      const ticket = crypto.randomUUID();
      await this.ctx.storage.put(`ticket:${ticket}`, Date.now() + TICKET_TTL_MS);
      return Response.json({ ticket });
    }

    if (url.pathname === '/publish' && request.method === 'POST') {
      const message = await request.text();
      let sockets = 0;
      for (const ws of this.ctx.getWebSockets()) {
        try {
          ws.send(message);
          sockets++;
        } catch {
          /* closing */
        }
      }
      // How many tabs got it: > 0 means the user has UniVerse open right now.
      return Response.json({ sockets });
    }

    if (url.pathname === '/realtime') {
      const key = `ticket:${url.searchParams.get('ticket')}`;
      const expires = await this.ctx.storage.get<number>(key);
      if (!expires) return new Response('Forbidden', { status: 403 });
      await this.ctx.storage.delete(key); // single use
      if (expires < Date.now()) return new Response('Forbidden', { status: 403 });

      const open = this.ctx.getWebSockets();
      if (open.length >= MAX_SOCKETS) open[0].close(4000, 'Too many connections');
      const { 0: client, 1: server } = new WebSocketPair();
      this.ctx.acceptWebSocket(server);
      server.send(JSON.stringify({ type: 'hello' }));
      return new Response(null, { status: 101, webSocket: client });
    }

    return new Response('Not found', { status: 404 });
  }

  async webSocketMessage() {
    // Clients only send pings (auto-answered above).
  }

  async webSocketClose(ws: WebSocket, code: number) {
    try {
      ws.close(code === 1005 || code === 1006 ? 1000 : code);
    } catch {
      /* already closed */
    }
  }
}

// ─── Whiteboards ─────────────────────────────────────────────────────────────────────────────────

/** Who is on a board socket (kept on the socket so it survives hibernation). */
interface BoardPeer {
  sid: string; // this connection
  userId: string;
  name: string;
  avatar: string | null;
  color: string;
  canEdit: boolean;
}

/** The parts of an Excalidraw element the server needs to merge edits. */
interface BoardElement {
  id: string;
  version: number;
  versionNonce: number;
  isDeleted?: boolean;
  [key: string]: unknown;
}

interface BoardFile {
  id: string;
  mimeType: string;
  url: string; // an uploaded file (/api/files/… or the R2 files domain), never inline data
  created: number;
}

const MAX_ELEMENTS = 20_000;
const MAX_ELEMENT_BYTES = 256 * 1024; // one shape (a long freehand stroke is the biggest)
const MAX_FILES = 300;
const MAX_BOARD_SOCKETS = 60;
const PEER_COLORS = ['#6366f1', '#ec4899', '#f59e0b', '#10b981', '#0ea5e9', '#ef4444', '#8b5cf6', '#14b8a6', '#f97316', '#84cc16'];

/**
 * One per whiteboard: holds the board's shapes and pictures and everyone who has it open.
 * People edit locally and send the shapes they changed; the room keeps the newest version of each
 * shape (Excalidraw's version / versionNonce rules, so everyone ends up with the same drawing) and
 * passes the changes and live cursors on to the others. Viewers can watch but their edits are
 * ignored. Access is checked by the app, which hands out one-time tickets (/api/boards/[id]/ticket).
 */
export class BoardRoom extends DurableObject<Env> {
  private elementCount: number | undefined; // counted on first need after each wake-up

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    this.ctx.setWebSocketAutoResponse(new WebSocketRequestResponsePair('ping', 'pong'));
  }

  private peers(): { ws: WebSocket; peer: BoardPeer }[] {
    const out: { ws: WebSocket; peer: BoardPeer }[] = [];
    for (const ws of this.ctx.getWebSockets()) {
      const peer = ws.deserializeAttachment() as BoardPeer | null;
      if (peer) out.push({ ws, peer });
    }
    return out;
  }

  private broadcast(message: unknown, except?: WebSocket) {
    const text = JSON.stringify(message);
    for (const ws of this.ctx.getWebSockets()) {
      if (ws === except) continue;
      try {
        ws.send(text);
      } catch {
        /* closing */
      }
    }
  }

  private presence() {
    return this.peers().map(({ peer }) => ({ sid: peer.sid, userId: peer.userId, name: peer.name, avatar: peer.avatar, color: peer.color, canEdit: peer.canEdit }));
  }

  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);

    // From the app: a one-time ticket for someone allowed on the board.
    if (url.pathname === '/ticket' && request.method === 'POST') {
      const who = (await request.json()) as Omit<BoardPeer, 'sid' | 'color'>;
      const now = Date.now();
      const stale = [...(await this.ctx.storage.list<{ exp: number }>({ prefix: 'ticket:' }))].filter(([, t]) => t.exp < now).map(([k]) => k);
      if (stale.length) await this.ctx.storage.delete(stale.slice(0, 128));
      const ticket = crypto.randomUUID();
      await this.ctx.storage.put(`ticket:${ticket}`, { ...who, exp: now + TICKET_TTL_MS });
      return Response.json({ ticket });
    }

    // From the app: access changed (someone removed, a role or the link setting changed) or the
    // board was deleted. Matching people are disconnected; the app reconnects them if still allowed.
    if (url.pathname === '/kick' && request.method === 'POST') {
      const { userIds, all, wipe } = (await request.json()) as { userIds?: string[]; all?: boolean; wipe?: boolean };
      for (const { ws, peer } of this.peers()) {
        if (all || userIds?.includes(peer.userId)) {
          try {
            ws.close(wipe ? 4004 : 4003, wipe ? 'Board deleted' : 'Access changed');
          } catch {
            /* closed */
          }
        }
      }
      if (wipe) {
        await this.ctx.storage.deleteAll();
        this.elementCount = 0;
      }
      return Response.json({ ok: true });
    }

    // From the app: the drawing, for a copy of the board.
    if (url.pathname === '/snapshot' && request.method === 'GET') {
      return Response.json(await this.snapshot());
    }

    // From the app: fill a new board (a copy).
    if (url.pathname === '/seed' && request.method === 'POST') {
      const { elements, files } = (await request.json()) as { elements: BoardElement[]; files: BoardFile[] };
      const batch: Record<string, unknown> = {};
      for (const el of elements.slice(0, MAX_ELEMENTS)) if (validElement(el)) batch[`el:${el.id}`] = el;
      for (const f of files.slice(0, MAX_FILES)) if (validFile(f)) batch[`file:${f.id}`] = f;
      const entries = Object.entries(batch);
      for (let i = 0; i < entries.length; i += 128) await this.ctx.storage.put(Object.fromEntries(entries.slice(i, i + 128)));
      this.elementCount = undefined;
      return Response.json({ ok: true });
    }

    if (url.pathname === '/board-live') {
      const key = `ticket:${url.searchParams.get('ticket')}`;
      const who = await this.ctx.storage.get<Omit<BoardPeer, 'sid' | 'color'> & { exp: number }>(key);
      if (!who) return new Response('Forbidden', { status: 403 });
      await this.ctx.storage.delete(key); // single use
      if (who.exp < Date.now()) return new Response('Forbidden', { status: 403 });

      const open = this.ctx.getWebSockets();
      if (open.length >= MAX_BOARD_SOCKETS) return new Response('This board is full', { status: 429 });
      const used = new Set(this.peers().map(({ peer }) => peer.color));
      const color = PEER_COLORS.find((c) => !used.has(c)) ?? PEER_COLORS[open.length % PEER_COLORS.length];
      const peer: BoardPeer = { sid: crypto.randomUUID().slice(0, 8), userId: who.userId, name: who.name, avatar: who.avatar, color, canEdit: who.canEdit };

      const { 0: client, 1: server } = new WebSocketPair();
      this.ctx.acceptWebSocket(server);
      server.serializeAttachment(peer);
      const { elements, files } = await this.snapshot();
      server.send(JSON.stringify({ type: 'init', me: peer, elements, files, peers: this.presence() }));
      this.broadcast({ type: 'peers', peers: this.presence() }, server);
      return new Response(null, { status: 101, webSocket: client });
    }

    return new Response('Not found', { status: 404 });
  }

  private async snapshot() {
    const [els, files] = await Promise.all([
      this.ctx.storage.list<BoardElement>({ prefix: 'el:' }),
      this.ctx.storage.list<BoardFile>({ prefix: 'file:' }),
    ]);
    return { elements: [...els.values()], files: [...files.values()] };
  }

  async webSocketMessage(ws: WebSocket, raw: string | ArrayBuffer) {
    const peer = ws.deserializeAttachment() as BoardPeer | null;
    if (!peer || typeof raw !== 'string') return;
    let msg: { type?: string; [key: string]: unknown };
    try {
      msg = JSON.parse(raw);
    } catch {
      return;
    }

    if (msg.type === 'cursor') {
      // Where someone's pointer is: passed on, never stored.
      const { x, y, tool, button, selected } = msg as { x?: unknown; y?: unknown; tool?: unknown; button?: unknown; selected?: unknown };
      if (typeof x !== 'number' || typeof y !== 'number' || !Number.isFinite(x) || !Number.isFinite(y)) return;
      this.broadcast({
        type: 'cursor',
        sid: peer.sid,
        x,
        y,
        tool: tool === 'laser' ? 'laser' : 'pointer',
        button: button === 'down' ? 'down' : 'up',
        selected: Array.isArray(selected) ? selected.filter((s) => typeof s === 'string').slice(0, 200) : [],
      }, ws);
      return;
    }

    if (!peer.canEdit) return; // viewers watch only

    if (msg.type === 'update' && Array.isArray(msg.elements)) {
      const incoming = (msg.elements as BoardElement[]).filter(validElement);
      if (!incoming.length) return;
      const current = new Map<string, BoardElement>();
      for (let i = 0; i < incoming.length; i += 128) {
        for (const [k, v] of await this.ctx.storage.get<BoardElement>(incoming.slice(i, i + 128).map((e) => `el:${e.id}`))) current.set(k, v);
      }
      const accepted: BoardElement[] = [];
      for (const el of incoming) {
        const have = current.get(`el:${el.id}`);
        if (!have) {
          this.elementCount ??= (await this.ctx.storage.list({ prefix: 'el:' })).size;
          if (this.elementCount >= MAX_ELEMENTS) continue;
          this.elementCount++;
        } else if (!(el.version > have.version || (el.version === have.version && el.versionNonce < have.versionNonce))) {
          continue; // we already have this edit or a newer one
        }
        accepted.push(el);
      }
      if (!accepted.length) return;
      for (let i = 0; i < accepted.length; i += 128) {
        await this.ctx.storage.put(Object.fromEntries(accepted.slice(i, i + 128).map((e) => [`el:${e.id}`, e])));
      }
      this.broadcast({ type: 'update', elements: accepted }, ws);
      await this.ctx.storage.put('meta:editedAt', Date.now());
      return;
    }

    if (msg.type === 'file' && msg.file && validFile(msg.file as BoardFile)) {
      const f = msg.file as BoardFile;
      const file: BoardFile = { id: f.id, mimeType: f.mimeType, url: f.url, created: Date.now() };
      if ((await this.ctx.storage.get(`file:${f.id}`)) == null) {
        if ((await this.ctx.storage.list({ prefix: 'file:' })).size >= MAX_FILES) return;
        await this.ctx.storage.put(`file:${f.id}`, file);
      }
      this.broadcast({ type: 'file', file }, ws);
    }
  }

  async webSocketClose(ws: WebSocket, code: number) {
    try {
      ws.close(code === 1005 || code === 1006 ? 1000 : code);
    } catch {
      /* already closed */
    }
    this.broadcast({ type: 'peers', peers: this.presence().filter((p) => p.sid !== (ws.deserializeAttachment() as BoardPeer | null)?.sid) });
  }
}

function validElement(el: unknown): el is BoardElement {
  if (!el || typeof el !== 'object') return false;
  const e = el as BoardElement;
  if (typeof e.id !== 'string' || e.id.length > 64 || typeof e.version !== 'number' || typeof e.versionNonce !== 'number' || typeof e.type !== 'string') return false;
  // Pictures must point at an uploaded file, never carry the image inline.
  return JSON.stringify(e).length <= MAX_ELEMENT_BYTES;
}

function validFile(f: BoardFile): boolean {
  return (
    !!f && typeof f.id === 'string' && f.id.length <= 128 &&
    typeof f.mimeType === 'string' && /^image\/(png|jpeg|gif|webp|svg\+xml)$/.test(f.mimeType) &&
    typeof f.url === 'string' && f.url.length <= 600 &&
    // An upload of ours: database storage (/api/files/…) or the R2 files domain (https). Browsers
    // only load these from our own storage (BoardCanvas + the Content-Security-Policy).
    (/^\/api\/files\/[A-Za-z0-9_-]{16,}\/[^?#\s]*$/.test(f.url) || /^https:\/\/[a-z0-9.-]+\/[^\s"'<>]+$/i.test(f.url))
  );
}

// ─── Code rooms ──────────────────────────────────────────────────────────────────────────────────

/** Who is on a code-room socket (kept on the socket so it survives hibernation). */
interface CodePeer { userId: string; name: string; canEdit: boolean }

const CODE_DOC = 0; // a Yjs document update
const CODE_AWARENESS = 1; // cursors and selections (y-protocols awareness), passed on, never stored
const CODE_ANNOUNCE = 2; // "someone joined: send your cursor again"
const MAX_CODE_BYTES = 512 * 1024;
const MAX_CODE_SOCKETS = 60;

/**
 * One per shared code editor (src/server/code-rooms.ts). Holds the document as a Yjs doc, so
 * simultaneous edits merge; passes cursor positions between people; ignores edits from people
 * who may only watch. Saved to storage at most about once a second (an alarm), not per keystroke.
 */
export class CodeRoom extends DurableObject<Env> {
  private doc: Y.Doc | null = null;
  private dirty = false;

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    this.ctx.setWebSocketAutoResponse(new WebSocketRequestResponsePair('ping', 'pong'));
  }

  private async load(): Promise<Y.Doc> {
    if (this.doc) return this.doc;
    const doc = new Y.Doc();
    const saved = await this.ctx.storage.get<Uint8Array>('doc');
    if (saved) Y.applyUpdate(doc, new Uint8Array(saved));
    this.doc = doc;
    return doc;
  }

  private send(ws: WebSocket, type: number, payload?: Uint8Array) {
    const msg = new Uint8Array(1 + (payload?.length ?? 0));
    msg[0] = type;
    if (payload) msg.set(payload, 1);
    try { ws.send(msg); } catch { /* closing */ }
  }

  private relay(from: WebSocket, data: ArrayBuffer) {
    for (const ws of this.ctx.getWebSockets()) if (ws !== from) try { ws.send(data); } catch { /* closing */ }
  }

  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);
    if (url.pathname === '/ticket' && request.method === 'POST') {
      const who = (await request.json()) as CodePeer;
      const now = Date.now();
      const stale = [...(await this.ctx.storage.list<{ exp: number }>({ prefix: 'ticket:' }))].filter(([, t]) => t.exp < now).map(([k]) => k);
      if (stale.length) await this.ctx.storage.delete(stale.slice(0, 128));
      const ticket = crypto.randomUUID();
      await this.ctx.storage.put(`ticket:${ticket}`, { ...who, exp: now + TICKET_TTL_MS });
      return Response.json({ ticket });
    }
    if (url.pathname === '/kick' && request.method === 'POST') {
      const { wipe } = (await request.json()) as { wipe?: boolean };
      for (const ws of this.ctx.getWebSockets()) try { ws.close(wipe ? 4004 : 4003, wipe ? 'Room deleted' : 'Access changed'); } catch { /* closed */ }
      if (wipe) { await this.ctx.storage.deleteAll(); this.doc = null; this.dirty = false; }
      return Response.json({ ok: true });
    }
    if (url.pathname === '/code-live') {
      const key = `ticket:${url.searchParams.get('ticket')}`;
      const who = await this.ctx.storage.get<CodePeer & { exp: number }>(key);
      if (!who) return new Response('Forbidden', { status: 403 });
      await this.ctx.storage.delete(key); // single use
      if (who.exp < Date.now()) return new Response('Forbidden', { status: 403 });
      if (this.ctx.getWebSockets().length >= MAX_CODE_SOCKETS) return new Response('This room is full', { status: 429 });
      const { 0: client, 1: server } = new WebSocketPair();
      this.ctx.acceptWebSocket(server);
      server.serializeAttachment({ userId: who.userId, name: who.name, canEdit: who.canEdit } satisfies CodePeer);
      const doc = await this.load();
      this.send(server, CODE_DOC, Y.encodeStateAsUpdate(doc));
      for (const ws of this.ctx.getWebSockets()) if (ws !== server) this.send(ws, CODE_ANNOUNCE);
      return new Response(null, { status: 101, webSocket: client });
    }
    return new Response('Not found', { status: 404 });
  }

  async webSocketMessage(ws: WebSocket, raw: string | ArrayBuffer) {
    if (typeof raw === 'string' || raw.byteLength < 1 || raw.byteLength > MAX_CODE_BYTES) return;
    const peer = ws.deserializeAttachment() as CodePeer | null;
    if (!peer) return;
    const bytes = new Uint8Array(raw);
    if (bytes[0] === CODE_AWARENESS || bytes[0] === CODE_ANNOUNCE) {
      this.relay(ws, raw);
      return;
    }
    if (bytes[0] !== CODE_DOC || !peer.canEdit) return; // watchers can't edit
    const doc = await this.load();
    try {
      Y.applyUpdate(doc, bytes.subarray(1));
    } catch {
      return; // not a valid update
    }
    if (Y.encodeStateAsUpdate(doc).byteLength > MAX_CODE_BYTES) {
      // Too big: drop this change for everyone by reloading the last saved copy.
      this.doc = null;
      try { ws.close(4013, 'This file is too large'); } catch { /* closed */ }
      return;
    }
    this.relay(ws, raw);
    if (!this.dirty) {
      this.dirty = true;
      await this.ctx.storage.setAlarm(Date.now() + 1000);
    }
  }

  async alarm() {
    if (!this.dirty || !this.doc) return;
    this.dirty = false;
    await this.ctx.storage.put('doc', Y.encodeStateAsUpdate(this.doc));
  }

  async webSocketClose(ws: WebSocket, code: number) {
    try { ws.close(code === 1005 || code === 1006 ? 1000 : code); } catch { /* already closed */ }
    // Last one out: save now rather than waiting for the alarm.
    if (this.ctx.getWebSockets().length <= 1) await this.alarm();
  }
}

// ─── Calls ───────────────────────────────────────────────────────────────────────────────────────

/** A track someone sends to Cloudflare's SFU (bigger calls), which others pull by name. */
interface SfuTrack { trackName: string; kind: 'audio' | 'video' }
/** Someone in a call (kept on the socket so it survives hibernation). host: the teacher, the room's
 *  moderators or the link's creator; cohost: given host controls by the host during the call. */
interface CallPeer { peerId: string; userId: string; name: string; host?: boolean; cohost?: boolean; hand?: number; waiting?: boolean; sfu?: { sessionId: string; tracks: SfuTrack[] }; ccLang?: string | null; ccDevice?: boolean; pulse?: 'lost' | 'got' | null }
interface CallTicket { userId: string; name: string; exp: number; host?: boolean; max?: number }

const MAX_CALL_PEERS = 6; // small calls: everyone connects to everyone
const MAX_SFU_PEERS = 150; // bigger calls through the SFU (the app sets the real cap per ticket)
const MAX_SIGNAL_BYTES = 64 * 1024;
const MAX_CAPTION = 300;
/**
 * Translated captions (Stage 4 · 4.1): each person reads captions in their own language. Every
 * finished sentence gets an id; for each language someone reads in (other than the speaker's), the
 * room asks ONE of those readers to translate it (preferring one whose browser translates on the
 * device, for free) and shares the result with everyone reading that language.
 */
const langBase = (v: unknown) => (typeof v === 'string' && /^[a-z]{2,3}(?:[-_][A-Za-z0-9]{2,8})*$/i.test(v) ? v.split(/[-_]/)[0].toLowerCase() : null);
const MAX_CAPTION_TR = 600;
/**
 * Classroom pulse (Stage 4 · 4.4): students tap "I'm lost" or "Got it" (their app clears it after
 * two minutes). Only counts reach the hosts, at most every PULSE_PUSH_MS; nobody's tap is ever sent
 * with their name (see publicPeer).
 */
const PULSE_PUSH_MS = 800;
/** A person as the others in the call see them: without their pulse. */
const publicPeer = (p: CallPeer): Omit<CallPeer, 'pulse'> => { const { pulse, ...rest } = p; void pulse; return rest; };
/** Reactions anyone can send (floating emoji), and how many per person in a few seconds. */
const REACTIONS = new Set(['👍', '👏', '❤️', '😂', '😮', '🎉']);
const REACTION_BURST = 8, REACTION_WINDOW_MS = 4000;
/** Someone the host removed can't come back into the same call for this long; someone let in from
 *  the waiting room comes straight back in for as long. */
const REMOVED_MS = 4 * 3600_000;
const MAX_WAITING = 50;
/** The call's own chat (calls without a chat of their own): kept while the call lasts. */
const CHAT_KEEP = 100, CHAT_MAX_CHARS = 2000, CHAT_BURST = 6, CHAT_WINDOW_MS = 5000;
interface RoomChat { id: string; uid: string; name: string; text: string; at: number; file?: { url: string; name: string; size: number; mime: string } | null }
/** A chat message as one person sees it: whether it's theirs, without anyone's account id. */
const chatView = (l: RoomChat, viewer: string) => ({ id: l.id, name: l.name, text: l.text, at: l.at, file: l.file ?? null, mine: l.uid === viewer });
/** An uploaded file's address: this app's own files, or the files bucket (https). */
const safeFile = (f: unknown): RoomChat['file'] => {
  const x = f as { url?: unknown; name?: unknown; size?: unknown; mime?: unknown } | null;
  if (!x || typeof x.url !== 'string' || x.url.length > 600 || !(/^\/api\/files\/[A-Za-z0-9_-]{16,}/.test(x.url) || /^https:\/\/[^/]+\//.test(x.url))) return null;
  return { url: x.url, name: String(x.name ?? 'file').slice(0, 120), size: Math.max(0, Number(x.size) || 0), mime: String(x.mime ?? '').slice(0, 100) };
};
/**
 * Breakout rooms (Stage 4 · 2.6): the host splits the call into smaller rooms for a while. Each room
 * is a call room of its own, `<call>~b<n>`; the main call's room keeps the plan (who goes where, the
 * timer) and tells the rooms about changes. People move between rooms in the app, keeping their
 * camera and microphone. `k` is a short key per person, so hosts can move people without anyone's
 * account id reaching the app.
 */
interface Breakout {
  id: string;
  rooms: { n: number; name: string }[];
  people: { k: string; userId: string; name: string; n: number }[];
  /** When the rooms close by themselves (the timer), and when everyone goes back (30 s after closing starts). */
  endsAt: number | null;
  closing: number | null;
  /** People pick their own room. */
  choose: boolean;
  /** The host's latest message to every room. */
  note: { text: string; by: string; at: number } | null;
}
/** Who is in each room now (the rooms report it): names, and whether a host is there. */
type Occupancy = Record<number, { names: string[]; hosts: boolean }>;
const MAX_ROOMS = 20, BO_CLOSE_MS = 30_000, MAX_BO_MINUTES = 120, BO_NOTE_CHARS = 300;
/** A breakout room's id → the main call and the room's number. */
const childOf = (id: string | null) => {
  const m = id ? /^(.+)~b(\d{1,2})$/.exec(id) : null;
  const n = m ? Number(m[2]) : 0;
  return m && n >= 1 && n <= MAX_ROOMS ? { parent: m[1], n } : null;
};

/**
 * A live poll or quick quiz in a call (Stage 4 · 2.7), one at a time, kept while the call lasts.
 * Votes are per person (changing your answer while it's open replaces it). Names are only kept for
 * the hosts' view when the poll isn't anonymous.
 */
interface CallPoll {
  id: string; q: string; options: string[]; quiz: boolean; correct: number | null; anon: boolean;
  by: string; at: number; open: boolean;
  votes: Record<string, number>;
  names: Record<string, string>;
}
const POLL_Q_CHARS = 200, POLL_OPTION_CHARS = 80, POLL_MAX_OPTIONS = 6, POLL_PUSH_MS = 700;

const SFU_API = 'https://rtc.live.cloudflare.com/v1/apps';
/** Simulcast camera layers: a 720p, b 360p, c 180p (src/lib/sfu-client.ts). */
const isLayer = (rid: unknown): rid is 'a' | 'b' | 'c' => rid === 'a' || rid === 'b' || rid === 'c';

/**
 * One per call (src/server/calls.ts). Passes WebRTC connection details (offers, answers, network
 * candidates) between the people in the call and tells everyone who joined, left, muted, turned
 * their camera off, is recording, and what they said (live captions, made in each speaker's
 * browser). Small calls go browser to browser; bigger ones (CALLS_APP_ID and CALLS_APP_SECRET set)
 * go through Cloudflare's SFU, which this room talks to so the app secret never leaves the server
 * and a browser can only touch its own SFU session. Nothing is stored except one-time join tickets.
 */
export class CallRoom extends DurableObject<Env> {
  /** Recent reactions and chat messages per person (burst limits; forgotten when the room sleeps). */
  private reacted = new Map<string, number[]>();
  private chatted = new Map<string, number[]>();
  /** This room's call id, and when each person last asked the hosts for help (breakout rooms). */
  private self: string | null = null;
  private helped = new Map<string, number>();
  /** Poll results go out at most every POLL_PUSH_MS while people vote (a class answering at once). */
  private pollSentAt = 0;
  private pollTimer: ReturnType<typeof setTimeout> | null = null;
  /** Finished captions so far, and who was asked to translate which (caption id + language). */
  private captionSeq = 0;
  private trAsked = new Map<string, string>();
  private pulseSentAt = 0;
  private pulseTimer: ReturnType<typeof setTimeout> | null = null;

  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    this.ctx.setWebSocketAutoResponse(new WebSocketRequestResponsePair('ping', 'pong'));
  }

  private sockets() {
    return this.ctx.getWebSockets().map((ws) => ({ ws, peer: ws.deserializeAttachment() as CallPeer | null })).filter((p): p is { ws: WebSocket; peer: CallPeer } => !!p.peer);
  }

  /** Everyone in the call (not the waiting room). */
  private peers() {
    return this.sockets().filter(({ peer }) => !peer.waiting);
  }

  /** People in the waiting room, until the host lets them in. */
  private waitingRoom() {
    return this.sockets().filter(({ peer }) => peer.waiting);
  }

  /** Whoever can let people in: the host and co-hosts. */
  private mods(except?: WebSocket) {
    return this.peers().filter(({ ws, peer }) => ws !== except && (peer.host || peer.cohost));
  }

  /** Tells the waiting room whether a host is here to let them in. */
  private tellWaiting(except?: WebSocket) {
    const hostHere = this.mods(except).length > 0;
    for (const { ws } of this.waitingRoom()) this.send(ws, { type: 'lobby', hostHere });
  }

  /** Into the call: the newcomer calls everyone already here (so two never offer to each other at once). */
  private async join(ws: WebSocket, me: CallPeer, lobbyOn: boolean) {
    const current = this.peers().filter((p) => p.ws !== ws);
    const mod = me.host === true || me.cohost === true;
    // Breakout rooms: the plan, kept here (the main call) or asked from the main call (a room).
    const child = childOf(await this.selfId());
    const res = child ? await this.parentFetch('/breakout-state', {}) : null;
    const plan = child
      ? ((await res?.json().catch(() => null)) as { bo: Breakout | null; occ: Occupancy } | null) ?? { bo: null, occ: {} }
      : { bo: await this.boLoad(), occ: await this.occupancy() };
    this.send(ws, {
      type: 'welcome', you: me.peerId, host: me.host === true, cohost: me.cohost === true,
      peers: current.map(({ peer }) => publicPeer(peer)),
      spotlight: (await this.ctx.storage.get<string>('spotlight')) ?? null,
      lobbyOn, lobby: mod ? this.waitingRoom().map(({ peer }) => ({ peerId: peer.peerId, name: peer.name })) : [],
      chat: [...(await this.ctx.storage.list<RoomChat>({ prefix: 'chat:', reverse: true, limit: CHAT_KEEP })).values()].reverse().map((l) => chatView(l, me.userId)),
      bo: this.boView(plan.bo, plan.occ, me), room: child?.n ?? null,
      poll: this.pollView((await this.ctx.storage.get<CallPoll>('poll')) ?? null, me),
      pulse: mod ? this.pulseCounts() : null,
    });
    for (const { ws: other } of current) this.send(other, { type: 'joined', peer: publicPeer(me) });
    this.pulseTell();
    if (mod) this.tellWaiting();
    if (child) await this.reportRoom();
  }

  private send(ws: WebSocket, msg: unknown) {
    try { ws.send(JSON.stringify(msg)); } catch { /* closing */ }
  }

  /** How many students are lost or follow right now, of how many (hosts and co-hosts don't count). */
  private pulseCounts(except?: WebSocket) {
    const students = this.peers().filter(({ ws, peer }) => ws !== except && !peer.host && !peer.cohost);
    return { lost: students.filter(({ peer }) => peer.pulse === 'lost').length, got: students.filter(({ peer }) => peer.pulse === 'got').length, total: students.length };
  }

  /** Sends the counts to the hosts (throttled: a class tapping at once is one update). */
  private pulseTell(now = false, except?: WebSocket) {
    if (!now && Date.now() - this.pulseSentAt < PULSE_PUSH_MS) {
      this.pulseTimer ??= setTimeout(() => { this.pulseTimer = null; this.pulseTell(true); }, PULSE_PUSH_MS);
      return;
    }
    this.pulseSentAt = Date.now();
    const counts = this.pulseCounts(except);
    for (const { ws } of this.mods(except)) this.send(ws, { type: 'pulse', ...counts });
  }

  /** A finished caption: one reader per other language translates it for the rest (see langBase). */
  private askTranslators(speaker: WebSocket, id: string, lang: string) {
    const byLang = new Map<string, { ws: WebSocket; peer: CallPeer }[]>();
    for (const p of this.peers()) {
      if (p.ws === speaker || !p.peer.ccLang || p.peer.ccLang === lang) continue;
      byLang.set(p.peer.ccLang, [...(byLang.get(p.peer.ccLang) ?? []), p]);
    }
    for (const [to, readers] of byLang) {
      const pick = readers.find((r) => r.peer.ccDevice) ?? readers[0];
      this.trAsked.set(`${id}|${to}`, pick.peer.peerId);
      this.send(pick.ws, { type: 'cc-do', id, lang: to });
    }
    // Only recent requests matter (a translation comes back in seconds).
    if (this.trAsked.size > 400) for (const k of [...this.trAsked.keys()].slice(0, 200)) this.trAsked.delete(k);
  }

  private others(ws: WebSocket, msg: unknown) {
    const text = JSON.stringify(msg);
    for (const { ws: other } of this.peers()) if (other !== ws) try { other.send(text); } catch { /* closing */ }
  }

  private async sfu(path: string, method: string, body?: unknown): Promise<Record<string, unknown>> {
    const app = this.env.CALLS_APP_ID, secret = this.env.CALLS_APP_SECRET;
    if (typeof app !== 'string' || typeof secret !== 'string' || !app || !secret) throw new Error('Bigger calls aren’t set up.');
    const res = await fetch(`${SFU_API}/${encodeURIComponent(app)}${path}`, {
      method,
      headers: { Authorization: `Bearer ${secret}`, 'Content-Type': 'application/json' },
      body: body === undefined ? undefined : JSON.stringify(body),
    });
    const out = (await res.json().catch(() => ({}))) as Record<string, unknown>;
    if (!res.ok || out.errorCode) throw new Error(String(out.errorDescription ?? `SFU ${res.status}`));
    return out;
  }

  // ── Live polls and quick quizzes ───────────────────────────────────────────────────────────────

  /**
   * A poll as one person sees it. Results: hosts always; everyone else once they've answered a poll,
   * or when it ends. A quiz shows nobody else's answers, nor the right one, until the host ends it.
   */
  private pollView(p: CallPoll | null, peer: CallPeer) {
    if (!p) return null;
    const mod = peer.host === true || peer.cohost === true;
    const mine = p.votes[peer.userId] ?? null;
    const counts = p.options.map((_, i) => Object.values(p.votes).filter((v) => v === i).length);
    const show = mod || !p.open || (!p.quiz && mine !== null);
    return {
      id: p.id, q: p.q, options: p.options, quiz: p.quiz, anon: p.anon, by: p.by, open: p.open,
      mine, total: Object.keys(p.votes).length, counts: show ? counts : null,
      correct: p.quiz && (mod || !p.open) ? p.correct : null,
      ...(mod && !p.anon ? { voters: p.options.map((_, i) => Object.entries(p.votes).filter(([, v]) => v === i).map(([u]) => p.names[u] ?? 'Someone')) } : {}),
    };
  }

  /** Everyone sees the poll as it is now (at most every POLL_PUSH_MS unless `now`). */
  private async pollTell(now = false) {
    if (!now && Date.now() - this.pollSentAt < POLL_PUSH_MS) {
      this.pollTimer ??= setTimeout(() => { this.pollTimer = null; void this.pollTell(true); }, POLL_PUSH_MS);
      return;
    }
    this.pollSentAt = Date.now();
    const p = (await this.ctx.storage.get<CallPoll>('poll')) ?? null;
    for (const { ws, peer } of this.peers()) this.send(ws, { type: 'poll', poll: this.pollView(p, peer) });
  }

  /** The host starts a poll or quiz (replacing the last one), ends it, or takes it away. */
  private async pollControl(me: CallPeer, msg: Record<string, unknown>) {
    if (msg.action === 'poll-start') {
      const q = typeof msg.q === 'string' ? msg.q.trim().slice(0, POLL_Q_CHARS) : '';
      const options = (Array.isArray(msg.options) ? msg.options : []).map((o) => String(o ?? '').trim().slice(0, POLL_OPTION_CHARS)).filter(Boolean).slice(0, POLL_MAX_OPTIONS);
      if (!q || options.length < 2) return;
      const quiz = msg.quiz === true;
      const correct = quiz && Number.isInteger(msg.correct) && (msg.correct as number) >= 0 && (msg.correct as number) < options.length ? (msg.correct as number) : null;
      if (quiz && correct === null) return;
      const poll: CallPoll = { id: crypto.randomUUID().slice(0, 8), q, options, quiz, correct, anon: msg.anon !== false, by: me.name, at: Date.now(), open: true, votes: {}, names: {} };
      await this.ctx.storage.put('poll', poll);
    } else if (msg.action === 'poll-end') {
      const poll = await this.ctx.storage.get<CallPoll>('poll');
      if (!poll?.open) return;
      poll.open = false;
      await this.ctx.storage.put('poll', poll);
    } else if (msg.action === 'poll-clear') {
      await this.ctx.storage.delete('poll');
    } else return;
    await this.pollTell(true);
  }

  // ── Breakout rooms ─────────────────────────────────────────────────────────────────────────────

  /** This room's call id (from the join address; kept, since the room forgets between calls). */
  private async selfId(): Promise<string | null> {
    this.self ??= (await this.ctx.storage.get<string>('self')) ?? null;
    return this.self;
  }

  private async boLoad() {
    return (await this.ctx.storage.get<Breakout>('bo')) ?? null;
  }

  private async occupancy(): Promise<Occupancy> {
    const out: Occupancy = {};
    for (const [k, v] of await this.ctx.storage.list<Occupancy[number]>({ prefix: 'bocc:' })) out[Number(k.slice(5))] = v;
    return out;
  }

  /** The plan as one person sees it: their own room; hosts also see who goes where and who's in each room. */
  private boView(bo: Breakout | null, occ: Occupancy, peer: CallPeer) {
    if (!bo) return null;
    const mod = peer.host === true || peer.cohost === true;
    const mine = bo.people.find((p) => p.userId === peer.userId)?.n ?? 0;
    return {
      id: bo.id, endsAt: bo.endsAt, closing: bo.closing, choose: bo.choose, note: bo.note, mine: mine || null,
      rooms: bo.rooms.map((r) => ({ n: r.n, name: r.name, count: occ[r.n]?.names.length ?? 0, ...(mod ? { here: occ[r.n]?.names ?? [] } : {}) })),
      ...(mod ? { people: bo.people.map(({ k, name, n }) => ({ k, name, n })) } : {}),
    };
  }

  /** Tells everyone connected here about the plan (each sees their own view). */
  private boTell(bo: Breakout | null, occ: Occupancy, onlyMods = false) {
    for (const { ws, peer } of this.peers()) if (!onlyMods || peer.host || peer.cohost) this.send(ws, { type: 'breakout', bo: this.boView(bo, occ, peer) });
  }

  /** The main call: sends something to its rooms that have people in them (or only those a host is in). */
  private async relay(rooms: number[], body: unknown, onlyWithHosts = false) {
    const self = await this.selfId(), ns = this.env.CALLS;
    if (!self || !ns) return;
    const occ = await this.occupancy();
    const to = rooms.filter((n) => (occ[n]?.names.length ?? 0) > 0 && (!onlyWithHosts || occ[n]?.hosts));
    await Promise.all(to.map((n) => ns.get(ns.idFromName(`${self}~b${n}`)).fetch('https://call/relay', { method: 'POST', body: JSON.stringify(body) }).catch(() => null)));
  }

  /** The main call: everyone here and in the rooms hears about a change to the plan. */
  private async boShare(bo: Breakout) {
    const occ = await this.occupancy();
    this.boTell(bo, occ);
    await this.relay(bo.rooms.map((r) => r.n), { kind: 'state', bo, occ });
  }

  /** A breakout room: asks the main call's room. */
  private async parentFetch(path: string, body: unknown): Promise<Response | null> {
    const child = childOf(await this.selfId()), ns = this.env.CALLS;
    if (!child || !ns) return null;
    try { return await ns.get(ns.idFromName(child.parent)).fetch(`https://call${path}`, { method: 'POST', body: JSON.stringify(body) }); } catch { return null; }
  }

  /** A breakout room: tells the main call who's here now (hosts see it live). */
  private async reportRoom(except?: WebSocket) {
    const child = childOf(await this.selfId());
    if (!child) return;
    const here = this.peers().filter(({ ws }) => ws !== except);
    await this.parentFetch('/breakout-occupancy', { n: child.n, names: here.map(({ peer }) => peer.name).slice(0, 60), hosts: here.some(({ peer }) => peer.host || peer.cohost) });
  }

  /** The rooms close: everyone goes back to the main call. */
  private async boEnd(bo: Breakout) {
    await this.ctx.storage.delete(['bo', ...(await this.ctx.storage.list({ prefix: 'bocc:' })).keys()]);
    await this.ctx.storage.deleteAlarm();
    this.boTell(null, {});
    const self = await this.selfId(), ns = this.env.CALLS;
    if (self && ns) await Promise.all(bo.rooms.map((r) => ns.get(ns.idFromName(`${self}~b${r.n}`)).fetch('https://call/relay', { method: 'POST', body: JSON.stringify({ kind: 'state', bo: null, occ: {} }) }).catch(() => null)));
  }

  /** The timer runs out (the rooms start closing), and 30 s later everyone goes back. */
  async alarm() {
    const bo = await this.boLoad();
    if (!bo) return;
    const now = Date.now();
    if (bo.closing && now >= bo.closing - 250) return this.boEnd(bo);
    if (bo.endsAt && !bo.closing && now >= bo.endsAt - 250) {
      bo.closing = now + BO_CLOSE_MS;
      await this.ctx.storage.put('bo', bo);
      await this.ctx.storage.setAlarm(bo.closing);
      return this.boShare(bo);
    }
    const next = bo.closing ?? bo.endsAt;
    if (next) await this.ctx.storage.setAlarm(next);
  }

  /**
   * The host's breakout controls, in the main call's room (from a host here, or forwarded by a room a
   * host is visiting): open the rooms, move someone, message every room, set the timer, close.
   */
  private async boControl(actor: { userId: string; name: string }, msg: Record<string, unknown>) {
    const now = Date.now();
    let bo = await this.boLoad();
    const action = msg.action;
    if (action === 'bo-open') {
      if (bo) return;
      const count = Math.max(1, Math.min(MAX_ROOMS, Math.round(Number(msg.rooms) || 0)));
      const names = Array.isArray(msg.names) ? (msg.names as unknown[]) : [];
      const rooms = Array.from({ length: count }, (_, i) => {
        const given = names[i];
        return { n: i + 1, name: (typeof given === 'string' && given.trim() ? given.trim() : `Room ${i + 1}`).slice(0, 40) };
      });
      const assign = (msg.assign && typeof msg.assign === 'object' ? msg.assign : {}) as Record<string, unknown>;
      const people: Breakout['people'] = [];
      for (const { peer } of this.peers()) {
        const n = Math.round(Number(assign[peer.peerId]) || 0);
        if (n < 1 || n > count || people.some((p) => p.userId === peer.userId)) continue;
        people.push({ k: crypto.randomUUID().slice(0, 8), userId: peer.userId, name: peer.name, n });
      }
      const minutes = Math.max(0, Math.min(MAX_BO_MINUTES, Math.round(Number(msg.minutes) || 0)));
      bo = { id: crypto.randomUUID().slice(0, 8), rooms, people, endsAt: minutes ? now + minutes * 60_000 : null, closing: null, choose: msg.choose === true, note: null };
      await this.ctx.storage.put('bo', bo);
      if (bo.endsAt) await this.ctx.storage.setAlarm(bo.endsAt);
      return this.boShare(bo);
    }
    if (!bo) return;
    if (action === 'bo-assign') {
      // Move one person (by their key, or someone in the main call by their peer id); room 0 = the main call.
      const n = Math.round(Number(msg.n) || 0);
      if (n < 0 || n > bo.rooms.length) return;
      let person = typeof msg.k === 'string' ? bo.people.find((p) => p.k === msg.k) : undefined;
      if (!person && typeof msg.target === 'string') {
        const peer = this.peers().find(({ peer: p }) => p.peerId === msg.target)?.peer;
        if (!peer) return;
        person = bo.people.find((p) => p.userId === peer.userId);
        if (!person) { person = { k: crypto.randomUUID().slice(0, 8), userId: peer.userId, name: peer.name, n: 0 }; bo.people.push(person); }
      }
      if (!person) return;
      person.n = n;
    } else if (action === 'bo-note' && typeof msg.text === 'string' && msg.text.trim()) {
      bo.note = { text: msg.text.trim().slice(0, BO_NOTE_CHARS), by: actor.name, at: now };
    } else if (action === 'bo-time') {
      const minutes = Math.max(0, Math.min(MAX_BO_MINUTES, Math.round(Number(msg.minutes) || 0)));
      bo.endsAt = minutes ? now + minutes * 60_000 : null;
      if (!bo.closing) {
        if (bo.endsAt) await this.ctx.storage.setAlarm(bo.endsAt);
        else await this.ctx.storage.deleteAlarm();
      }
    } else if (action === 'bo-close') {
      if (bo.closing) return;
      bo.closing = now + BO_CLOSE_MS;
      await this.ctx.storage.setAlarm(bo.closing);
    } else if (action === 'bo-end') {
      return this.boEnd(bo);
    } else return;
    await this.ctx.storage.put('bo', bo);
    await this.boShare(bo);
  }

  /** Someone picks their own room, when the host lets people choose (0: the main call). */
  private async boPick(peer: { userId: string; name: string }, n: unknown) {
    const bo = await this.boLoad();
    const room = Math.round(Number(n) || 0);
    if (!bo?.choose || bo.closing || room < 0 || room > bo.rooms.length) return;
    const person = bo.people.find((p) => p.userId === peer.userId);
    if (person) person.n = room;
    else bo.people.push({ k: crypto.randomUUID().slice(0, 8), userId: peer.userId, name: peer.name, n: room });
    await this.ctx.storage.put('bo', bo);
    await this.boShare(bo);
  }

  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);
    // ── Breakout rooms: from the app (/breakout-pass) or between call rooms, never from browsers ──
    if (url.pathname.startsWith('/breakout-') || url.pathname === '/relay') {
      if (request.method !== 'POST') return new Response('Not found', { status: 404 });
      const body = (await request.json().catch(() => ({}))) as Record<string, unknown>;
      const bo = await this.boLoad();
      if (url.pathname === '/breakout-pass') {
        // May this person join room n? Their own room, any room when people choose, any room for hosts.
        const userId = typeof body.userId === 'string' ? body.userId : '';
        const room = bo?.rooms.find((r) => r.n === body.n);
        if (!bo || !room || !userId) return Response.json({ error: 'These breakout rooms have closed.' }, { status: 404 });
        if (((await this.ctx.storage.get<{ until: number }>(`removed:${userId}`))?.until ?? 0) > Date.now()) return Response.json({ error: 'removed' }, { status: 403 });
        const mod = body.host === true || (await this.ctx.storage.get<string>('creator')) === userId || !!(await this.ctx.storage.get(`cohost:${userId}`));
        if (!mod && !bo.choose && bo.people.find((p) => p.userId === userId)?.n !== room.n) return Response.json({ error: 'This breakout room is for other people.' }, { status: 403 });
        return Response.json({ ok: true, host: mod, name: room.name });
      }
      if (url.pathname === '/breakout-state') return Response.json({ bo, occ: await this.occupancy() });
      if (url.pathname === '/breakout-host') {
        // A host's control from a room they're visiting.
        const actor = body.actor as { userId?: unknown; name?: unknown } | undefined;
        if (typeof actor?.userId === 'string' && body.msg && typeof body.msg === 'object') await this.boControl({ userId: actor.userId, name: String(actor.name ?? 'The host').slice(0, 80) }, body.msg as Record<string, unknown>);
      } else if (url.pathname === '/breakout-pick') {
        if (typeof body.userId === 'string') await this.boPick({ userId: body.userId, name: String(body.name ?? 'Someone').slice(0, 80) }, body.n);
      } else if (url.pathname === '/breakout-occupancy') {
        const n = typeof body.n === 'number' ? body.n : 0;
        if (bo && bo.rooms.some((r) => r.n === n)) {
          await this.ctx.storage.put(`bocc:${n}`, { names: Array.isArray(body.names) ? body.names.slice(0, 60).map((x) => String(x).slice(0, 80)) : [], hosts: body.hosts === true });
          // Hosts see who's in each room, live: here, and in any room a host is visiting.
          const occ = await this.occupancy();
          this.boTell(bo, occ, true);
          await this.relay(bo.rooms.map((r) => r.n), { kind: 'state', bo, occ }, true);
        }
      } else if (url.pathname === '/breakout-help') {
        const room = bo?.rooms.find((r) => r.n === body.n);
        if (bo && room) {
          const help = { type: 'bo-help', n: room.n, room: room.name, by: String(body.name ?? 'Someone').slice(0, 80) };
          for (const { ws } of this.mods()) this.send(ws, help);
          await this.relay(bo.rooms.map((r) => r.n).filter((x) => x !== room.n), { kind: 'help', help }, true);
        }
      } else if (url.pathname === '/relay') {
        // A breakout room, from the main call: the plan changed, or someone in another room asks for help.
        if (body.kind === 'state') this.boTell((body.bo as Breakout | null) ?? null, (body.occ as Occupancy) ?? {});
        else if (body.kind === 'help') for (const { ws } of this.mods()) this.send(ws, body.help);
      }
      return Response.json({ ok: true });
    }
    if (url.pathname === '/ticket' && request.method === 'POST') {
      const who = (await request.json()) as Omit<CallTicket, 'exp'>;
      const now = Date.now();
      const stale = [
        ...[...(await this.ctx.storage.list<{ exp: number }>({ prefix: 'ticket:' }))].filter(([, t]) => t.exp < now),
        ...[...(await this.ctx.storage.list<{ until: number }>({ prefix: 'removed:' }))].filter(([, t]) => t.until < now),
        ...[...(await this.ctx.storage.list<{ until: number }>({ prefix: 'admitted:' }))].filter(([, t]) => t.until < now),
      ].map(([k]) => k);
      if (stale.length) await this.ctx.storage.delete(stale.slice(0, 128));
      // An empty room starts a new call: the last call's chat goes.
      if (!this.sockets().length) await this.clearChat();
      // Removed by the host: not back into this call (for a few hours).
      if (((await this.ctx.storage.get<{ until: number }>(`removed:${who.userId}`))?.until ?? 0) > now) return Response.json({ error: 'removed' }, { status: 403 });
      // A call link's creator hosts it.
      if (who.userId && (await this.ctx.storage.get<string>('creator')) === who.userId) who.host = true;
      const ticket = crypto.randomUUID();
      await this.ctx.storage.put(`ticket:${ticket}`, { ...who, exp: now + TICKET_TTL_MS });
      return Response.json({ ticket });
    }
    // From the app: who made this call link (they host it).
    if (url.pathname === '/creator' && request.method === 'POST') {
      const { userId } = (await request.json()) as { userId?: string };
      if (userId && !(await this.ctx.storage.get('creator'))) await this.ctx.storage.put('creator', userId);
      return Response.json({ ok: true });
    }
    // From the app: who is in the room (names only), for voice channel lists.
    if (url.pathname === '/peers') {
      const peers = this.peers().map(({ peer }) => peer.name);
      return Response.json({ count: peers.length, names: peers.slice(0, 12) });
    }
    // From the app: someone declined (sent to everyone waiting in the call).
    if (url.pathname === '/notify' && request.method === 'POST') {
      const note = (await request.json()) as { type: string; name: string };
      for (const { ws } of this.peers()) this.send(ws, { type: note.type === 'declined' ? 'declined' : 'note', name: String(note.name ?? '').slice(0, 80) });
      return Response.json({ ok: true });
    }
    if (url.pathname === '/call-live') {
      // This room's call id (breakout rooms need it to find the main call, and the main call its rooms).
      const callParam = url.searchParams.get('call');
      if (callParam && !(await this.selfId())) { this.self = callParam; await this.ctx.storage.put('self', callParam); }
      const key = `ticket:${url.searchParams.get('ticket')}`;
      const who = await this.ctx.storage.get<CallTicket>(key);
      if (!who) return new Response('Forbidden', { status: 403 });
      await this.ctx.storage.delete(key); // single use
      if (who.exp < Date.now()) return new Response('Forbidden', { status: 403 });
      const current = this.peers();
      if (current.length >= Math.min(MAX_SFU_PEERS, who.max ?? MAX_CALL_PEERS)) return new Response('This call is full', { status: 429 });
      const me: CallPeer = { peerId: crypto.randomUUID().slice(0, 12), userId: who.userId, name: who.name, host: who.host === true };
      // Co-hosts stay co-hosts when they reconnect.
      if (!me.host && (await this.ctx.storage.get(`cohost:${who.userId}`))) me.cohost = true;
      // Waiting room: on for call links (with a creator to let people in; older links have none)
      // unless their host turned it off; a host can turn it on for any call. Hosts, co-hosts and
      // anyone let in during the last few hours go straight in.
      const lobbyOn = (await this.ctx.storage.get<boolean>('lobby')) ?? ((url.searchParams.get('call') ?? '').startsWith('l_') && !!(await this.ctx.storage.get('creator')));
      const admitted = me.host || me.cohost || ((await this.ctx.storage.get<{ until: number }>(`admitted:${who.userId}`))?.until ?? 0) > Date.now();
      if (lobbyOn && !admitted && this.waitingRoom().length >= MAX_WAITING) return new Response('The waiting room is full', { status: 429 });
      const { 0: client, 1: server } = new WebSocketPair();
      this.ctx.acceptWebSocket(server);
      if (lobbyOn && !admitted) {
        me.waiting = true;
        server.serializeAttachment(me);
        this.send(server, { type: 'lobby', hostHere: this.mods().length > 0 });
        for (const { ws } of this.mods()) this.send(ws, { type: 'knock', peer: { peerId: me.peerId, name: me.name } });
        return new Response(null, { status: 101, webSocket: client });
      }
      server.serializeAttachment(me);
      await this.join(server, me, lobbyOn);
      return new Response(null, { status: 101, webSocket: client });
    }
    return new Response('Not found', { status: 404 });
  }

  async webSocketMessage(ws: WebSocket, raw: string | ArrayBuffer) {
    if (typeof raw !== 'string' || raw.length > MAX_SIGNAL_BYTES) return;
    const me = ws.deserializeAttachment() as CallPeer | null;
    // In the waiting room nothing goes to the call.
    if (!me || me.waiting) return;
    let msg: { type?: string; to?: string; data?: unknown; muted?: unknown; camera?: unknown; sharing?: unknown; cc?: unknown; recording?: unknown; notes?: unknown; lowData?: unknown; text?: unknown; final?: unknown; lang?: unknown; device?: unknown; v?: unknown; id?: unknown; op?: unknown; sdp?: unknown; tracks?: unknown; mids?: unknown; action?: unknown; target?: unknown; on?: unknown; up?: unknown; emoji?: unknown; file?: unknown; n?: unknown };
    try { msg = JSON.parse(raw); } catch { return; }
    if (msg.type === 'signal' && typeof msg.to === 'string') {
      const target = this.peers().find(({ peer }) => peer.peerId === msg.to);
      if (target) this.send(target.ws, { type: 'signal', from: me.peerId, data: msg.data });
      return;
    }
    if (msg.type === 'state') {
      // Only the class's teacher (or an admin) can record or take class notes; everyone sees the
      // REC and Notes badges.
      this.others(ws, { type: 'state', from: me.peerId, muted: msg.muted === true, camera: msg.camera !== false, sharing: msg.sharing === true, cc: msg.cc === true, recording: me.host === true && msg.recording === true, notes: me.host === true && msg.notes === true, lowData: msg.lowData === true });
      return;
    }
    if (msg.type === 'caption' && typeof msg.text === 'string') {
      const text = msg.text.trim().slice(-MAX_CAPTION);
      if (!text) return;
      const final = msg.final === true, lang = langBase(msg.lang);
      const id = final ? `${me.peerId}.${++this.captionSeq}` : undefined;
      this.others(ws, { type: 'caption', from: me.peerId, text, final, lang, id });
      if (id && lang) this.askTranslators(ws, id, lang);
      return;
    }
    if (msg.type === 'pulse') {
      if (me.host || me.cohost) return;
      const v = msg.v === 'lost' || msg.v === 'got' ? msg.v : null;
      if ((me.pulse ?? null) === v) return;
      me.pulse = v;
      ws.serializeAttachment(me);
      this.pulseTell();
      return;
    }
    if (msg.type === 'cc-lang') {
      // The language I read captions in (null: captions off, or as spoken).
      me.ccLang = langBase(msg.lang);
      me.ccDevice = msg.device === true;
      ws.serializeAttachment(me);
      return;
    }
    if (msg.type === 'cc-tr' && typeof msg.id === 'string' && typeof msg.text === 'string') {
      // A translation I was asked for: to everyone else reading that language.
      const to = langBase(msg.lang);
      const key = `${msg.id}|${to}`;
      if (!to || this.trAsked.get(key) !== me.peerId) return;
      this.trAsked.delete(key);
      const out = JSON.stringify({ type: 'cc-tr', id: msg.id, lang: to, text: msg.text.trim().slice(0, MAX_CAPTION_TR) });
      for (const { ws: other, peer } of this.peers()) if (other !== ws && peer.ccLang === to) try { other.send(out); } catch { /* closing */ }
      return;
    }
    if (msg.type === 'hand') {
      // Raised hands queue by when they went up (kept on the socket, so newcomers see the queue).
      this.setHand(me, ws, msg.up === true);
      return;
    }
    if (msg.type === 'react' && typeof msg.emoji === 'string' && REACTIONS.has(msg.emoji)) {
      const now = Date.now();
      const recent = (this.reacted.get(me.peerId) ?? []).filter((t) => now - t < REACTION_WINDOW_MS);
      if (recent.length >= REACTION_BURST) return;
      this.reacted.set(me.peerId, [...recent, now]);
      this.others(ws, { type: 'react', from: me.peerId, emoji: msg.emoji });
      return;
    }
    if (msg.type === 'chat') {
      // The call's own chat: text (links stay links) and uploaded files, to everyone in the call.
      const text = typeof msg.text === 'string' ? msg.text.trim().slice(0, CHAT_MAX_CHARS) : '';
      const file = safeFile(msg.file);
      if (!text && !file) return;
      const now = Date.now();
      const recent = (this.chatted.get(me.peerId) ?? []).filter((t) => now - t < CHAT_WINDOW_MS);
      if (recent.length >= CHAT_BURST) return;
      this.chatted.set(me.peerId, [...recent, now]);
      const line: RoomChat = { id: `${now.toString(36)}-${crypto.randomUUID().slice(0, 6)}`, uid: me.userId, name: me.name, text, at: now, file };
      await this.ctx.storage.put(`chat:${String(now).padStart(15, '0')}:${line.id}`, line);
      for (const { ws: p, peer } of this.peers()) this.send(p, { type: 'chat', line: chatView(line, peer.userId) });
      return;
    }
    if (msg.type === 'control' && typeof msg.action === 'string') {
      if (msg.action.startsWith('bo-')) {
        // Breakout rooms: run by the main call's room (forwarded when the host is visiting a room).
        if (!me.host && !me.cohost) return;
        if (childOf(await this.selfId())) await this.parentFetch('/breakout-host', { actor: { userId: me.userId, name: me.name }, msg });
        else await this.boControl({ userId: me.userId, name: me.name }, msg as Record<string, unknown>);
        return;
      }
      if (msg.action.startsWith('poll-')) {
        if (me.host || me.cohost) await this.pollControl(me, msg as Record<string, unknown>);
        return;
      }
      await this.control(ws, me, msg.action, typeof msg.target === 'string' ? msg.target : null, msg.on === true);
      return;
    }
    if (msg.type === 'vote') {
      // An answer to the open poll (a new answer replaces the last one while it's open).
      const poll = await this.ctx.storage.get<CallPoll>('poll');
      const choice = Number(msg.n);
      if (!poll?.open || poll.id !== msg.id || !Number.isInteger(choice) || choice < 0 || choice >= poll.options.length) return;
      poll.votes[me.userId] = choice;
      poll.names[me.userId] = me.name;
      await this.ctx.storage.put('poll', poll);
      this.send(ws, { type: 'poll', poll: this.pollView(poll, me) });
      await this.pollTell();
      return;
    }
    if (msg.type === 'bo-pick') {
      // Picking my own breakout room, when the host lets people choose.
      if (childOf(await this.selfId())) await this.parentFetch('/breakout-pick', { userId: me.userId, name: me.name, n: msg.n });
      else await this.boPick(me, msg.n);
      return;
    }
    if (msg.type === 'bo-help') {
      // From a breakout room: ask the hosts to come (once every 30 s per person).
      const child = childOf(await this.selfId());
      const now = Date.now();
      if (!child || now - (this.helped.get(me.userId) ?? 0) < 30_000) return;
      this.helped.set(me.userId, now);
      await this.parentFetch('/breakout-help', { n: child.n, name: me.name });
      return;
    }
    if (msg.type === 'sfu' && typeof msg.id === 'number') {
      try {
        this.send(ws, { type: 'sfu', id: msg.id, data: await this.sfuOp(ws, me, msg) });
      } catch (e) {
        this.send(ws, { type: 'sfu', id: msg.id, error: (e as Error).message });
      }
    }
  }

  /** Forgets the call's own chat and its poll (the call is over). */
  private async clearChat() {
    await this.ctx.storage.delete('poll');
    for (;;) {
      const keys = [...(await this.ctx.storage.list({ prefix: 'chat:', limit: 128 })).keys()];
      if (!keys.length) return;
      await this.ctx.storage.delete(keys);
    }
  }

  /** Raises or lowers someone's hand, and tells everyone (the time orders the queue). */
  private setHand(peer: CallPeer, ws: WebSocket, up: boolean) {
    if (!!peer.hand === up) return;
    peer.hand = up ? Date.now() : undefined;
    ws.serializeAttachment(peer);
    const text = JSON.stringify({ type: 'hand', peerId: peer.peerId, at: peer.hand ?? null });
    for (const { ws: p } of this.peers()) try { p.send(text); } catch { /* closing */ }
  }

  /**
   * Host controls (src/components/call/PeoplePanel.tsx): from the host or a co-host only. Muting asks
   * the person's app to mute (it can't be undone remotely: unmuting is only ever asked for).
   */
  private async control(ws: WebSocket, me: CallPeer, action: string, target: string | null, on: boolean) {
    if (!me.host && !me.cohost) return;
    const all = this.peers();
    const them = target ? all.find(({ peer }) => peer.peerId === target) : undefined;
    const by = me.name;
    if (action === 'admit' || action === 'admit-all' || action === 'deny') {
      // The waiting room: let one or everyone in, or turn someone away.
      const knocking = this.waitingRoom().filter(({ peer }) => action === 'admit-all' || peer.peerId === target);
      for (const w of knocking) {
        if (action === 'deny') {
          this.send(w.ws, { type: 'denied', by });
          w.ws.serializeAttachment(null);
          try { w.ws.close(4003, 'Not let in'); } catch { /* already closed */ }
        } else {
          w.peer.waiting = false;
          w.ws.serializeAttachment(w.peer);
          await this.ctx.storage.put(`admitted:${w.peer.userId}`, { until: Date.now() + REMOVED_MS });
          await this.join(w.ws, w.peer, true);
        }
        for (const m of this.mods()) this.send(m.ws, { type: 'lobby-left', peerId: w.peer.peerId, admitted: action !== 'deny', name: w.peer.name, by });
      }
    } else if (action === 'lobby') {
      // Waiting room on or off; off lets everyone waiting in.
      await this.ctx.storage.put('lobby', on);
      for (const m of this.mods()) this.send(m.ws, { type: 'lobby-setting', on, by });
      if (!on) await this.control(ws, me, 'admit-all', null, false);
    } else if (action === 'lower-hand' && them) {
      this.setHand(them.peer, them.ws, false);
    } else if (action === 'lower-all') {
      for (const p of all) this.setHand(p.peer, p.ws, false);
    } else if ((action === 'mute' || action === 'ask-unmute' || action === 'stop-video') && them && them.ws !== ws) {
      this.send(them.ws, { type: 'control', action, by });
    } else if (action === 'mute-all') {
      for (const p of all) if (p.ws !== ws && !p.peer.host && !p.peer.cohost) this.send(p.ws, { type: 'control', action: 'mute', by, all: true });
    } else if (action === 'spotlight') {
      // Everyone sees this person large (target null: back to the grid).
      const id = them?.peer.peerId ?? null;
      if (id) await this.ctx.storage.put('spotlight', id);
      else await this.ctx.storage.delete('spotlight');
      for (const p of all) this.send(p.ws, { type: 'spotlight', peerId: id, by });
    } else if (action === 'cohost') {
      // Only the call's own host gives or takes host controls.
      if (!me.host || !them || them.peer.host) return;
      them.peer.cohost = on;
      them.ws.serializeAttachment(them.peer);
      if (on) await this.ctx.storage.put(`cohost:${them.peer.userId}`, true);
      else await this.ctx.storage.delete(`cohost:${them.peer.userId}`);
      for (const p of all) this.send(p.ws, { type: 'role', peerId: them.peer.peerId, cohost: on, by });
    } else if (action === 'remove') {
      // Not the host, and a co-host only by the host. Every device of theirs leaves, and they can't
      // come back into this call for a few hours.
      if (!them || them.ws === ws || them.peer.host || (them.peer.cohost && !me.host)) return;
      await this.ctx.storage.put(`removed:${them.peer.userId}`, { until: Date.now() + REMOVED_MS });
      const gone = all.filter(({ peer }) => peer.userId === them.peer.userId);
      for (const g of gone) {
        this.send(g.ws, { type: 'removed', by });
        g.ws.serializeAttachment(null);
        try { g.ws.close(4001, 'Removed from the call'); } catch { /* already closed */ }
      }
      for (const p of all) if (!gone.includes(p)) for (const g of gone) this.send(p.ws, { type: 'left', peerId: g.peer.peerId });
      const lit = await this.ctx.storage.get<string>('spotlight');
      if (gone.some((g) => g.peer.peerId === lit)) {
        await this.ctx.storage.delete('spotlight');
        for (const p of all) if (!gone.includes(p)) this.send(p.ws, { type: 'spotlight', peerId: null });
      }
    }
  }

  /** One step of joining or changing what someone sends or receives through the SFU. */
  private async sfuOp(ws: WebSocket, me: CallPeer, msg: { op?: unknown; sdp?: unknown; tracks?: unknown; mids?: unknown }) {
    const sdp = typeof msg.sdp === 'string' ? msg.sdp : null;
    if (msg.op === 'session') {
      if (!me.sfu) {
        const out = await this.sfu('/sessions/new', 'POST');
        me.sfu = { sessionId: String(out.sessionId), tracks: [] };
        ws.serializeAttachment(me);
      }
      return { sessionId: me.sfu.sessionId };
    }
    if (!me.sfu) throw new Error('No SFU session yet.');
    const session = `/sessions/${encodeURIComponent(me.sfu.sessionId)}`;
    const tracks = Array.isArray(msg.tracks) ? (msg.tracks as Record<string, unknown>[]).slice(0, 64) : [];
    if (msg.op === 'push' && sdp) {
      // Your own tracks only, named after you.
      const mine = tracks.filter((t) => typeof t.mid === 'string' && typeof t.trackName === 'string' && t.trackName.startsWith(`${me.peerId}-`) && (t.kind === 'audio' || t.kind === 'video'));
      const out = await this.sfu(`${session}/tracks/new`, 'POST', {
        sessionDescription: { type: 'offer', sdp },
        tracks: mine.map((t) => ({ location: 'local', mid: t.mid, trackName: t.trackName })),
      });
      const added = mine.map((t) => ({ trackName: String(t.trackName), kind: t.kind as SfuTrack['kind'] }));
      me.sfu.tracks = [...me.sfu.tracks.filter((t) => !added.some((a) => a.trackName === t.trackName)), ...added];
      ws.serializeAttachment(me);
      this.others(ws, { type: 'tracks', from: me.peerId, sessionId: me.sfu.sessionId, tracks: me.sfu.tracks });
      return out;
    }
    if (msg.op === 'pull') {
      // Only tracks of people in this call.
      const offered = new Map(this.peers().filter(({ peer }) => peer.sfu && peer.peerId !== me.peerId).map(({ peer }) => [peer.sfu!.sessionId, peer.sfu!.tracks]));
      const want = tracks.filter((t) => typeof t.sessionId === 'string' && offered.get(t.sessionId)?.some((o) => o.trackName === t.trackName));
      if (!want.length) return { tracks: [] };
      // Cameras are sent in three sizes (simulcast); ask for the one this viewer wants. Should the SFU
      // refuse that (a camera sent by an older app in one size), pull them plainly.
      const plain = want.map((t) => ({ location: 'remote', sessionId: t.sessionId, trackName: t.trackName }));
      const layered = want.map((t, i) => (isLayer(t.rid) ? { ...plain[i], simulcast: { preferredRid: t.rid, priorityOrdering: 'asciibetical', ridNotAvailable: 'asciibetical' } } : plain[i]));
      if (!layered.some((t) => 'simulcast' in t)) return this.sfu(`${session}/tracks/new`, 'POST', { tracks: plain });
      return this.sfu(`${session}/tracks/new`, 'POST', { tracks: layered }).catch(() => this.sfu(`${session}/tracks/new`, 'POST', { tracks: plain }));
    }
    if (msg.op === 'layer') {
      // A different camera size for tracks already received.
      const change = tracks.filter((t) => typeof t.sessionId === 'string' && typeof t.trackName === 'string' && typeof t.mid === 'string' && isLayer(t.rid));
      if (!change.length) return {};
      return this.sfu(`${session}/tracks/update`, 'PUT', { tracks: change.map((t) => ({ location: 'remote', sessionId: t.sessionId, trackName: t.trackName, mid: t.mid, simulcast: { preferredRid: t.rid } })) });
    }
    if (msg.op === 'renegotiate' && sdp) return this.sfu(`${session}/renegotiate`, 'PUT', { sessionDescription: { type: 'answer', sdp } });
    if (msg.op === 'close' && Array.isArray(msg.mids)) {
      const mids = msg.mids.filter((m): m is string => typeof m === 'string').slice(0, 64);
      if (!mids.length) return {};
      return this.sfu(`${session}/tracks/close`, 'PUT', { tracks: mids.map((mid) => ({ mid })), force: true });
    }
    throw new Error('Unknown SFU step.');
  }

  async webSocketClose(ws: WebSocket, code: number) {
    const me = ws.deserializeAttachment() as CallPeer | null;
    try { ws.close(code === 1005 || code === 1006 ? 1000 : code); } catch { /* already closed */ }
    if (!me) return;
    if (me.waiting) {
      // Gave up waiting.
      for (const { ws: m } of this.mods(ws)) this.send(m, { type: 'lobby-left', peerId: me.peerId });
      return;
    }
    const rest = this.peers().filter(({ ws: other }) => other !== ws);
    for (const { ws: other } of rest) this.send(other, { type: 'left', peerId: me.peerId });
    if (!me.host && !me.cohost) this.pulseTell(false, ws);
    await this.reportRoom(ws);
    // The last one out: the call's chat goes with the call.
    if (!rest.length) await this.clearChat();
    // The last host left: the waiting room hears nobody can let them in for now.
    if (me.host || me.cohost) this.tellWaiting(ws);
    // The spotlit person left: back to the grid.
    if ((await this.ctx.storage.get<string>('spotlight')) === me.peerId) {
      await this.ctx.storage.delete('spotlight');
      for (const { ws: other } of rest) this.send(other, { type: 'spotlight', peerId: null });
    }
  }
}
