// The Worker's entry point (wrangler.jsonc "main"). It wraps the Next.js app built by OpenNext
// and adds what a Next.js app can't do on its own:
//   - /realtime: WebSockets for live updates, held by a RealtimeHub Durable Object per user
//   - scheduled(): the daily cron job (quiz reminders), see src/app/api/cron/daily/route.ts
import { DurableObject } from 'cloudflare:workers';
// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- the file only exists after a build
// @ts-ignore: generated by `opennextjs-cloudflare build`
import nextApp from '../.open-next/worker.js';

// eslint-disable-next-line @typescript-eslint/ban-ts-comment -- the file only exists after a build
// @ts-ignore: generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from '../.open-next/worker.js';

interface Env {
  REALTIME: DurableObjectNamespace<RealtimeHub>;
  API_RATE_LIMITER?: RateLimit; // per signed-in user (or per IP when signed out)
  IP_RATE_LIMITER?: RateLimit; // per IP, generous: stops floods from one address
  COSTLY_RATE_LIMITER?: RateLimit; // per user, for AI, email and uploads
  [key: string]: unknown;
}

// Endpoints that cost money or send email per call.
const COSTLY = /^\/api\/(ai|summarize|premium\/ai-report|support|upload|core\/files\/upload)(\/|$)/;

const tooMany = () =>
  Response.json({ error: 'Too many requests. Please wait a minute and try again.' }, { status: 429, headers: { 'Retry-After': '60' } });

/**
 * Rate limits for the API and live updates. Keyed by the signed-in user (the end of their token)
 * so a whole campus behind one Wi-Fi address isn't treated as one person, plus a generous
 * per-address cap against floods. Limiter checks are free and don't count as requests.
 */
async function rateLimited(request: Request, url: URL, env: Env): Promise<boolean> {
  const ip = request.headers.get('cf-connecting-ip') ?? 'unknown';
  const token = request.headers.get('authorization')?.slice(-40);
  const who = token ? `u:${token}` : `ip:${ip}`;
  const checks: Promise<{ success: boolean }>[] = [];
  if (env.IP_RATE_LIMITER) checks.push(env.IP_RATE_LIMITER.limit({ key: ip }));
  if (env.API_RATE_LIMITER) checks.push(env.API_RATE_LIMITER.limit({ key: who }));
  if (env.COSTLY_RATE_LIMITER && request.method !== 'GET' && COSTLY.test(url.pathname)) checks.push(env.COSTLY_RATE_LIMITER.limit({ key: who }));
  return (await Promise.all(checks)).some((r) => !r.success);
}

const TICKET_TTL_MS = 60_000;
const MAX_SOCKETS = 20; // per user: app + a few browser tabs

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    const url = new URL(request.url);
    // Stripe's webhook is signed and comes from Stripe's servers, so it's never rate limited.
    if ((url.pathname.startsWith('/api/') && !url.pathname.startsWith('/api/webhooks/')) || url.pathname === '/realtime') {
      if (await rateLimited(request, url, env)) return tooMany();
    }
    if (url.pathname === '/realtime') {
      if (request.headers.get('Upgrade')?.toLowerCase() !== 'websocket') return new Response('Expected a WebSocket', { status: 426 });
      const user = url.searchParams.get('user');
      if (!user || !url.searchParams.get('ticket') || !env.REALTIME) return new Response('Forbidden', { status: 403 });
      return env.REALTIME.get(env.REALTIME.idFromName(user)).fetch(request);
    }
    return nextApp.fetch(request, env, ctx);
  },

  async scheduled(controller: ScheduledController, env: Env, ctx: ExecutionContext) {
    // Run the job inside the Next.js app (where the database code lives). The random token only
    // exists in this isolate, so the route can't be triggered from outside.
    const token = crypto.randomUUID();
    (globalThis as { __universeCronToken?: string }).__universeCronToken = token;
    const res: Response = await nextApp.fetch(
      new Request('https://universeimpact.com/api/cron/daily', { method: 'POST', headers: { 'x-cron-token': token } }),
      env,
      ctx,
    );
    console.log(`cron ${controller.cron}: ${res.status} ${await res.text()}`);
    if (!res.ok) throw new Error(`Daily job failed with ${res.status}`);
  },
};

/**
 * One per user: holds that user's open WebSockets (hibernating while idle, so an open tab costs
 * nothing between events) and forwards "something changed" events to them.
 */
export class RealtimeHub extends DurableObject<Env> {
  constructor(ctx: DurableObjectState, env: Env) {
    super(ctx, env);
    // Keep-alive pings are answered without waking the object.
    this.ctx.setWebSocketAutoResponse(new WebSocketRequestResponsePair('ping', 'pong'));
  }

  async fetch(request: Request): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === '/ticket' && request.method === 'POST') {
      const now = Date.now();
      const stale = [...(await this.ctx.storage.list<number>({ prefix: 'ticket:' }))].filter(([, exp]) => exp < now).map(([k]) => k);
      if (stale.length) await this.ctx.storage.delete(stale.slice(0, 128));
      const ticket = crypto.randomUUID();
      await this.ctx.storage.put(`ticket:${ticket}`, Date.now() + TICKET_TTL_MS);
      return Response.json({ ticket });
    }

    if (url.pathname === '/publish' && request.method === 'POST') {
      const message = await request.text();
      let sockets = 0;
      for (const ws of this.ctx.getWebSockets()) {
        try {
          ws.send(message);
          sockets++;
        } catch {
          /* closing */
        }
      }
      // How many tabs got it: > 0 means the user has UniVerse open right now.
      return Response.json({ sockets });
    }

    if (url.pathname === '/realtime') {
      const key = `ticket:${url.searchParams.get('ticket')}`;
      const expires = await this.ctx.storage.get<number>(key);
      if (!expires) return new Response('Forbidden', { status: 403 });
      await this.ctx.storage.delete(key); // single use
      if (expires < Date.now()) return new Response('Forbidden', { status: 403 });

      const open = this.ctx.getWebSockets();
      if (open.length >= MAX_SOCKETS) open[0].close(4000, 'Too many connections');
      const { 0: client, 1: server } = new WebSocketPair();
      this.ctx.acceptWebSocket(server);
      server.send(JSON.stringify({ type: 'hello' }));
      return new Response(null, { status: 101, webSocket: client });
    }

    return new Response('Not found', { status: 404 });
  }

  async webSocketMessage() {
    // Clients only send pings (auto-answered above).
  }

  async webSocketClose(ws: WebSocket, code: number) {
    try {
      ws.close(code === 1005 || code === 1006 ? 1000 : code);
    } catch {
      /* already closed */
    }
  }
}
